version: '2'

services:
  webapplication1:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.debug
      args:
      - CONTAINER_PORT=${WEBAPPLICATION1_PORT}
      - SERVER_URLS=http://*:${WEBAPPLICATION1_PORT}
    ports:
    - "${HOST_PORT}:${WEBAPPLICATION1_PORT}"
    volumes:
    - ..:/app
